#!/usr/bin/env python3

import os

from lib.bwm import logger
from lib.bwm import main


if __name__ == "__main__":
    
    workdir = os.path.dirname(os.path.abspath(__file__))
    
    logger.setup(loglevel="DEBUG", logpath="log/bwm.log")
    bandwidth_monitor = main.Main(workdir)
    
    logger.log.debug("Workdir is: %s", workdir)
    bandwidth_monitor.run()
