version: '3.1'

services:
  bwm:
    image: racoon/bandwidth-monitor
    restart: always
    depends_on: 
      - influx
    networks:
      - bwm
    environment:
      DBTYPE: influxdb
      DBHOST: influx
      DBUSER: bwm
      DBPASSWORD: bwm
  influx:
    image: influxdb:latest
    networks:
      - bwm
    volumes:
      - bwm:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=bwm
      - INFLUXDB_USER=bwm
      - INFLUXDB_PASSWORD=bwm
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - bwm
    volumes:
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influx
    environment:
      - GF_SECURITY_ADMIN_USER=bwm
      - GF_SECURITY_ADMIN_PASSWORD=bwm

networks:
  bwm:

volumes:
  bwm:
