version: '3.1'

services:

  bwm:
    image: racoon/bandwidth-monitor
    restart: always
    depends_on: 
      - mongo
    networks:
      - bwm
    environment:
      DBTYPE: mongodb
      DBHOST: mongo
      DBUSER: bwm
      DBPASSWORD: bwm

  mongo:
    image: mongo
    restart: always
    networks:
      - bwm
    environment:
      MONGO_INITDB_ROOT_USERNAME: bwm
      MONGO_INITDB_ROOT_PASSWORD: bwm

  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    networks:
      - bwm
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: bwm
      ME_CONFIG_MONGODB_ADMINPASSWORD: bwm

networks:
  bwm:

volumes:
  bwm:
