version: 2
jobs:
  build:
    docker:
      - image: python:3.7-alpine
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Run bandwidth-monitor service
          command: python3 bandwidth-monitor/main.py &
      - run:
          name: Store PID in variable
          command: bwm_pid=$!
      - run:
          name: Wait for bandwidth-monitor to init and measure once
          command: sleep 15
      - run:
          name: Terminate bandwidth-monitor service
          command: kill -s SIGINT $bwm_pid
      - run:
          name: Output logs
          command: cat log/bwm.log

workflows:
  version: 2
  build:
    jobs:
      - build
