version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mkdir /tmp/bwm

      - run: 
          name: Building docker image
          command: docker build -t racoon/bandwidth-monitor .
      
      - run:
          name: Export docker container image
          command: docker save --output /tmp/bwm/bwm.tar racoon/bandwidth-monitor
      
      - persist_to_workspace:
          root: /tmp/bwm
          paths: 
            - bwm.tar
  test:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/bwm

      - run:
          name: Import bandwidth-monitor image
          command: docker import /tmp/bwm/bwm.tar racoon/bandwidth-monitor

      - run:
          name: Run a instance of bandwidth-monitor image
          command: docker run -d --rm --name bwm -e LOGLEVEL="debug" -e DBTYPE="tinydb" -v $PWD:/bwm/data racoon/bandwidth-monitor

      - run:
          name: Wait until the first measure was made
          command: sleep 15

      - run:
          name: Test if data was created
          command: if test -f data/bwm.json; then echo "success"; else echo "fail"; fi

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
