version: 2
jobs:
  build:
    docker:
      - image: python:3.7-alpine
    steps:
      - checkout
      - run: pwd
      - run: ls -l
  test:
    docker: 
      - image: python:3.7-alpine
    steps:
      - run:
          name: Output home dir
          command: 'echo $HOME' 

workflows:
  version: 2
  build:
    jobs:
      - build
  test:
    jobs:
      - test