version: 2

jobs:
  lint_pylint:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Install pylint
          command: pip3 install pylint pylint-fail-under
      - run:
          name: Linting code
          command: pylint-fail-under --fail-under 8.0 bwm && find ./bwm/ -type f -name "*.py" | xargs pylint-fail-under --fail-under 8.0
  

  # build:
  #   working_directory: ~/bwm
  #   machine: true
  #   steps:
  #     - checkout
  #     - run: mkdir docker
  #     - run: 
  #         name: Building docker image
  #         command: docker build -t racoon/bandwidth-monitor .
  #     - run:
  #         name: Export docker container image
  #         command: docker save --output ~/bwm/docker/bwm.tar racoon/bandwidth-monitor
  #     - persist_to_workspace:
  #         root: ~/bwm/docker
  #         paths: 
  #           - bwm.tar
  
  

workflows:
  version: 2
  build:
    jobs:
      # - build
      - lint_pylint
