version: 2

jobs:
  lint:
    docker:
      - image: racoon/pylama:latest
    working_directory: /code
    steps:
      - checkout
      - run:
          name: Lint code
          command: pylama /code
  
  # build:
  #   working_directory: ~/bwm
  #   machine: true
  #   steps:
  #     - checkout
  #     - run: mkdir docker
  #     - run: 
  #         name: Building docker image
  #         command: docker build -t racoon/bandwidth-monitor .
  #     - run:
  #         name: Export docker container image
  #         command: docker save --output ~/bwm/docker/bwm.tar racoon/bandwidth-monitor
  #     - persist_to_workspace:
  #         root: ~/bwm/docker
  #         paths: 
  #           - bwm.tar
  
  

workflows:
  version: 2
  build:
    jobs:
      # - build
      - lint
