version: 2

jobs:
  build:
    working_directory: ~/bwm
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      
      - run: mkdir docker

      - run: 
          name: Building docker image
          command: docker build -t racoon/bandwidth-monitor .
      
      - run:
          name: Export docker container image
          command: docker save --output docker/bwm.tar racoon/bandwidth-monitor && ls -l docker
      
      - persist_to_workspace:
          root: ~/bwm/docker
          paths: 
            - bwm.tar
  
  test:
    machine: true
    steps:
      - attach_workspace:
          at: ~/bwm/docker

      - run:
          name: Import bandwidth-monitor image
          command: docker load docker/bwm.tar racoon/bandwidth-monitor

      - run:
          name: Run a instance of bandwidth-monitor image
          command: docker run -d --rm --name bwm -e LOGLEVEL="debug" -e DBTYPE="tinydb" -v $PWD:/bwm/data racoon/bandwidth-monitor

      - run:
          name: Wait until the first measure was made
          command: sleep 15

      - run:
          name: Test if data was created
          command: if test -f data/bwm.json; then echo "success"; else echo "fail"; fi

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
