{
 "title": "BWM-Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Max Download Rate 12h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Max/12h",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_result",
     "query": "SELECT max(\"download\"), max(\"upload\") AS \"upload\" FROM \"speedtest_result\" WHERE $timeFilter GROUP BY time(12h) fill(null)",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "download" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Upload Rate 12h",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "alias": "Max/12h",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_result",
     "query": "SELECT max(\"download\"), max(\"upload\") AS \"upload\" FROM \"speedtest_result\" WHERE $timeFilter GROUP BY time(12h) fill(null)",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "download" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speedtest-Download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Download-Rate",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_result",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "down" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Measurements",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_result",
     "select": [
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Upload" ], "type": "alias" }
      ],
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ping" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speedtest Upload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Upload-Rate",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_result",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "upload" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Ping in ms",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest_result",
     "query": "SELECT mean(\"ping\") AS \"ping\" FROM \"speedtest_result\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ping" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}